//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComTrans.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.TripAddresses = new HashSet<TripAddress>();
        }
    
        public int Id { get; set; }
        [DisplayName("Адрес доставки")]
        public string Address1 { get; set; }
        public int OrderId { get; set; }
        [DisplayName("Координаты")]
        public string Coord { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripAddress> TripAddresses { get; set; }
    }
}
