//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComTrans.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TripAddress
    {
        public int Id { get; set; }
        public int AddressId { get; set; }
        public int TripId { get; set; }
        [DisplayName("Номер")]
        public Nullable<int> Num { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
