//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComTrans.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.TripAddresses = new HashSet<TripAddress>();
        }
    
        public int Id { get; set; }
        public int DriverId { get; set; }
        public int CarId { get; set; }
        [DisplayName("Оптимальный маршрут")]
        public string Route { get; set; }
        [DisplayName("Дата рейса")]
        public Nullable<System.DateTime> Date { get; set; }

       
        public virtual Car Car { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripAddress> TripAddresses { get; set; }
    }
}
